# Generated by Django 4.2.5 on 2023-10-27 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogAPI', '0005_alter_comment_commentdate_alter_post_postdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comment',
            field=models.ManyToManyField(blank=True, related_name='comments', to='blogAPI.comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blogAPI.post'),
        ),
    ]
